### ISSUE TITLE
Remove .vscode directory from gitignore

### ISSUE THREAD

**Issue by matthew-pm** [matthew-ia/cayo#100]
Add `.vscode` to the repo. This mainly includes dictionary stuff for spellchecking, which is helpful for writing docs. Only is gonna be used/seen by maintainers anyway, so it'd be fine to include it.

**Comment by matthew-ia** [comment]
There's actually no .vscode dir in the local repo I was working from, so this is probably actually old. Prob will still delete, so if any project config stuff for Code gets added later it'll be added.
