### ISSUE TITLE
Write Docs

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/cayo#14]
Document how the Cayo works in general, the use case, the config, and the caveats.

- [x] overview
  - [x] why Cayo?
  - [x] use case(s)
  - [x] how it works (high level)
  - [x] caveats
- [x] getting started
  - [x] install
  - [x] requirements
    - [x] template file (hybrid between SvelteKit's `__layout.svelte`, and Vite's `index.html`)
    - [x] Cayo Components
      - [x] props are primitive only ([#52](https://github.com/matthew-ia/cayo/issues/52))
      - [x] required prop `src`
      - [x] Entry files (are `src/` relative, how to reference in page markup)
    - [x] Entry files (the "render hook", how entry files work in general, etc.) 
- [x] config
- [x] template file examples
- [x] explain that global SCSS should be imported the vite way ([#43](https://github.com/matthew-ia/cayo/issues/43))
- [ ] ~~more runtime code example(s)?~~
- [ ] ~~Skeleton example~~
- [x] Default rollup plugins (Svelte, css, json)
- [x] How It Works (behind the scenes explanation of how some stuff works, for myself and anyone else who might want to fork this or use it as learning material)
- [ ] ~~Quirks~~
  - [ ] ~~CSS `url()` only works with an actual (remote) URL or a static asset path (public)~~
- [ ] ~~Show a custom preprocessor example?~~

**Comment by matthew-pm** [comment]
Also should add a **Comparison** section, for Cayo vs. Svelte Kit vs. [Elder.js](https://elderguide.com/tech/elderjs/). 
- Elder.js
  - is pretty similar 
  - requires more boilerplate
  - supports a ton of extra stuff Cayo does not (hooks, shortcodes, markdown, etc.)
  - is likely better for larger sites
  - is likely better for sites that rely on external data that needs to be rendered
  - want added SEO features
 - Cayo 
   - probably best when a significant amount of your page(s) will be static HTML
   - small to medium sized projects
   - its more like a utility than a framework
   - uses vite for dev (fast)
